/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 squat_interactive.glb --transform --types 
Files: squat_interactive.glb [7.99MB] > /app/applet/squat_interactive-transformed.glb [2.23MB] (72%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName =
  | 'ankle_dorsiflexion__posture'
  | 'ankle_eversion__posture'
  | 'bird_dog__posture'
  | 'breathing__posture'
  | 'bridge__posture'
  | 'clamshell__posture'
  | 'copenhagen__posture'
  | 'couch_stretch__posture'
  | 'dead_bug__posture'
  | 'doorway_pec_stretch__posture'
  | 'elbow_extension__posture'
  | 'elbow_flexion__posture'
  | 'finger_extension__posture'
  | 'forearm_rotation__posture'
  | 'grip__posture'
  | 'heel_raise__posture'
  | 'hinge__posture'
  | 'hip_abduction__posture'
  | 'hip_flexor_stretch__posture'
  | 'hip_thrust__posture'
  | 'jaw_open__posture'
  | 'lat_stretch__posture'
  | 'leg_raise__posture'
  | 'lunge__posture'
  | 'neck_extension__posture'
  | 'neck_flexion__posture'
  | 'neck_rotation__posture'
  | 'neck_side_bend__posture'
  | 'nerve_glide__posture'
  | 'nordic__posture'
  | 'prone_y_raise__posture'
  | 'quad_setting__posture'
  | 'row__posture'
  | 'serratus_punch__posture'
  | 'shoulder_abduction__posture'
  | 'shoulder_flexion__posture'
  | 'shoulder_rotation__posture'
  | 'side_bend__posture'
  | 'side_plank__posture'
  | 'single_leg_stance__posture'
  | 'sleeper_stretch__posture'
  | 'spine_extension__posture'
  | 'spine_flexion__posture'
  | 'squat__posture'
  | 'thumb_opposition__posture'
  | 'wall_slide__posture'
  | 'wrist_extension__posture'
  | 'wrist_flexion__posture'
  | 'ankle_dorsiflexion'
  | 'ankle_eversion'
  | 'bird_dog'
  | 'breathing'
  | 'bridge'
  | 'clamshell'
  | 'copenhagen'
  | 'couch_stretch'
  | 'dead_bug'
  | 'doorway_pec_stretch'
  | 'elbow_extension'
  | 'elbow_flexion'
  | 'finger_extension'
  | 'forearm_rotation'
  | 'grip'
  | 'heel_raise'
  | 'hinge'
  | 'hip_abduction'
  | 'hip_flexor_stretch'
  | 'hip_thrust'
  | 'jaw_open'
  | 'lat_stretch'
  | 'leg_raise'
  | 'lunge'
  | 'neck_extension'
  | 'neck_flexion'
  | 'neck_rotation'
  | 'neck_side_bend'
  | 'nerve_glide'
  | 'nordic'
  | 'prone_y_raise'
  | 'quad_setting'
  | 'row'
  | 'serratus_punch'
  | 'shoulder_abduction'
  | 'shoulder_flexion'
  | 'shoulder_rotation'
  | 'side_bend'
  | 'side_plank'
  | 'single_leg_stance'
  | 'sleeper_stretch'
  | 'spine_extension'
  | 'spine_flexion'
  | 'squat'
  | 'thumb_opposition'
  | 'wall_slide'
  | 'wrist_extension'
  | 'wrist_flexion'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    adductor_group__l: THREE.SkinnedMesh
    adductor_group__r: THREE.SkinnedMesh
    biceps_brachii__l: THREE.SkinnedMesh
    biceps_brachii__r: THREE.SkinnedMesh
    brachialis__l: THREE.SkinnedMesh
    brachialis__r: THREE.SkinnedMesh
    brachioradialis__l: THREE.SkinnedMesh
    brachioradialis__r: THREE.SkinnedMesh
    deep_neck_flexors__l: THREE.SkinnedMesh
    deep_neck_flexors__r: THREE.SkinnedMesh
    deltoid__l: THREE.SkinnedMesh
    deltoid__r: THREE.SkinnedMesh
    digastric__l: THREE.SkinnedMesh
    digastric__r: THREE.SkinnedMesh
    erector_spinae__l: THREE.SkinnedMesh
    erector_spinae__r: THREE.SkinnedMesh
    finger_extensors__l: THREE.SkinnedMesh
    finger_extensors__r: THREE.SkinnedMesh
    finger_flexors__l: THREE.SkinnedMesh
    finger_flexors__r: THREE.SkinnedMesh
    gastrocnemius__l: THREE.SkinnedMesh
    gastrocnemius__r: THREE.SkinnedMesh
    gluteus_maximus__l: THREE.SkinnedMesh
    gluteus_maximus__r: THREE.SkinnedMesh
    gluteus_medius__l: THREE.SkinnedMesh
    gluteus_medius__r: THREE.SkinnedMesh
    hamstrings__l: THREE.SkinnedMesh
    hamstrings__r: THREE.SkinnedMesh
    hand_intrinsics__l: THREE.SkinnedMesh
    hand_intrinsics__r: THREE.SkinnedMesh
    iliopsoas__l: THREE.SkinnedMesh
    iliopsoas__r: THREE.SkinnedMesh
    latissimus_dorsi__l: THREE.SkinnedMesh
    latissimus_dorsi__r: THREE.SkinnedMesh
    levator_scapulae__l: THREE.SkinnedMesh
    levator_scapulae__r: THREE.SkinnedMesh
    lower_trapezius__l: THREE.SkinnedMesh
    lower_trapezius__r: THREE.SkinnedMesh
    masseter__l: THREE.SkinnedMesh
    masseter__r: THREE.SkinnedMesh
    multifidus__l: THREE.SkinnedMesh
    multifidus__r: THREE.SkinnedMesh
    pectoralis_major__l: THREE.SkinnedMesh
    pectoralis_major__r: THREE.SkinnedMesh
    pectoralis_minor__l: THREE.SkinnedMesh
    pectoralis_minor__r: THREE.SkinnedMesh
    peroneals__l: THREE.SkinnedMesh
    peroneals__r: THREE.SkinnedMesh
    piriformis__l: THREE.SkinnedMesh
    piriformis__r: THREE.SkinnedMesh
    pronators__l: THREE.SkinnedMesh
    pronators__r: THREE.SkinnedMesh
    pterygoids__l: THREE.SkinnedMesh
    pterygoids__r: THREE.SkinnedMesh
    quadratus_lumborum__l: THREE.SkinnedMesh
    quadratus_lumborum__r: THREE.SkinnedMesh
    quadriceps__l: THREE.SkinnedMesh
    quadriceps__r: THREE.SkinnedMesh
    rectus_abdominis__l: THREE.SkinnedMesh
    rectus_abdominis__r: THREE.SkinnedMesh
    rectus_femoris__l: THREE.SkinnedMesh
    rectus_femoris__r: THREE.SkinnedMesh
    rhomboids__l: THREE.SkinnedMesh
    rhomboids__r: THREE.SkinnedMesh
    rotator_cuff__l: THREE.SkinnedMesh
    rotator_cuff__r: THREE.SkinnedMesh
    scalenes__l: THREE.SkinnedMesh
    scalenes__r: THREE.SkinnedMesh
    serratus_anterior__l: THREE.SkinnedMesh
    serratus_anterior__r: THREE.SkinnedMesh
    soleus__l: THREE.SkinnedMesh
    soleus__r: THREE.SkinnedMesh
    splenius__l: THREE.SkinnedMesh
    splenius__r: THREE.SkinnedMesh
    sternocleidomastoid__l: THREE.SkinnedMesh
    sternocleidomastoid__r: THREE.SkinnedMesh
    suboccipitals__l: THREE.SkinnedMesh
    suboccipitals__r: THREE.SkinnedMesh
    supinator__l: THREE.SkinnedMesh
    supinator__r: THREE.SkinnedMesh
    temporalis__l: THREE.SkinnedMesh
    temporalis__r: THREE.SkinnedMesh
    tfl__l: THREE.SkinnedMesh
    tfl__r: THREE.SkinnedMesh
    tibialis_anterior__l: THREE.SkinnedMesh
    tibialis_anterior__r: THREE.SkinnedMesh
    tibialis_posterior__l: THREE.SkinnedMesh
    tibialis_posterior__r: THREE.SkinnedMesh
    transversus_abdominis__l: THREE.SkinnedMesh
    transversus_abdominis__r: THREE.SkinnedMesh
    triceps_brachii__l: THREE.SkinnedMesh
    triceps_brachii__r: THREE.SkinnedMesh
    upper_trapezius__l: THREE.SkinnedMesh
    upper_trapezius__r: THREE.SkinnedMesh
    wrist_extensors__l: THREE.SkinnedMesh
    wrist_extensors__r: THREE.SkinnedMesh
    wrist_flexors__l: THREE.SkinnedMesh
    wrist_flexors__r: THREE.SkinnedMesh
    C1: THREE.Bone
    C2: THREE.Bone
    C3: THREE.Bone
    C4: THREE.Bone
    C5: THREE.Bone
    C6: THREE.Bone
    C7: THREE.Bone
    Hips: THREE.Bone
    L1: THREE.Bone
    L2: THREE.Bone
    L3: THREE.Bone
    L4: THREE.Bone
    L5: THREE.Bone
    T1: THREE.Bone
    T2: THREE.Bone
    T3: THREE.Bone
    T4: THREE.Bone
    T5: THREE.Bone
    T6: THREE.Bone
    T7: THREE.Bone
    T8: THREE.Bone
    T9: THREE.Bone
    T10: THREE.Bone
    T11: THREE.Bone
    T12: THREE.Bone
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/squat_interactive-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="PostureRoot">
          <group name="Armature">
            <primitive object={nodes.C1} />
            <primitive object={nodes.C2} />
            <primitive object={nodes.C3} />
            <primitive object={nodes.C4} />
            <primitive object={nodes.C5} />
            <primitive object={nodes.C6} />
            <primitive object={nodes.C7} />
            <primitive object={nodes.Hips} />
            <primitive object={nodes.L1} />
            <primitive object={nodes.L2} />
            <primitive object={nodes.L3} />
            <primitive object={nodes.L4} />
            <primitive object={nodes.L5} />
            <primitive object={nodes.T1} />
            <primitive object={nodes.T2} />
            <primitive object={nodes.T3} />
            <primitive object={nodes.T4} />
            <primitive object={nodes.T5} />
            <primitive object={nodes.T6} />
            <primitive object={nodes.T7} />
            <primitive object={nodes.T8} />
            <primitive object={nodes.T9} />
            <primitive object={nodes.T10} />
            <primitive object={nodes.T11} />
            <primitive object={nodes.T12} />
            <skinnedMesh name="adductor_group__l" geometry={nodes.adductor_group__l.geometry} material={nodes.adductor_group__l.material} skeleton={nodes.adductor_group__l.skeleton} />
            <skinnedMesh name="adductor_group__r" geometry={nodes.adductor_group__r.geometry} material={nodes.adductor_group__r.material} skeleton={nodes.adductor_group__r.skeleton} />
            <skinnedMesh name="biceps_brachii__l" geometry={nodes.biceps_brachii__l.geometry} material={nodes.biceps_brachii__l.material} skeleton={nodes.biceps_brachii__l.skeleton} />
            <skinnedMesh name="biceps_brachii__r" geometry={nodes.biceps_brachii__r.geometry} material={nodes.biceps_brachii__r.material} skeleton={nodes.biceps_brachii__r.skeleton} />
            <skinnedMesh name="brachialis__l" geometry={nodes.brachialis__l.geometry} material={nodes.brachialis__l.material} skeleton={nodes.brachialis__l.skeleton} />
            <skinnedMesh name="brachialis__r" geometry={nodes.brachialis__r.geometry} material={nodes.brachialis__r.material} skeleton={nodes.brachialis__r.skeleton} />
            <skinnedMesh name="brachioradialis__l" geometry={nodes.brachioradialis__l.geometry} material={nodes.brachioradialis__l.material} skeleton={nodes.brachioradialis__l.skeleton} />
            <skinnedMesh name="brachioradialis__r" geometry={nodes.brachioradialis__r.geometry} material={nodes.brachioradialis__r.material} skeleton={nodes.brachioradialis__r.skeleton} />
            <skinnedMesh name="deep_neck_flexors__l" geometry={nodes.deep_neck_flexors__l.geometry} material={nodes.deep_neck_flexors__l.material} skeleton={nodes.deep_neck_flexors__l.skeleton} />
            <skinnedMesh name="deep_neck_flexors__r" geometry={nodes.deep_neck_flexors__r.geometry} material={nodes.deep_neck_flexors__r.material} skeleton={nodes.deep_neck_flexors__r.skeleton} />
            <skinnedMesh name="deltoid__l" geometry={nodes.deltoid__l.geometry} material={nodes.deltoid__l.material} skeleton={nodes.deltoid__l.skeleton} />
            <skinnedMesh name="deltoid__r" geometry={nodes.deltoid__r.geometry} material={nodes.deltoid__r.material} skeleton={nodes.deltoid__r.skeleton} />
            <skinnedMesh name="digastric__l" geometry={nodes.digastric__l.geometry} material={nodes.digastric__l.material} skeleton={nodes.digastric__l.skeleton} />
            <skinnedMesh name="digastric__r" geometry={nodes.digastric__r.geometry} material={nodes.digastric__r.material} skeleton={nodes.digastric__r.skeleton} />
            <skinnedMesh name="erector_spinae__l" geometry={nodes.erector_spinae__l.geometry} material={nodes.erector_spinae__l.material} skeleton={nodes.erector_spinae__l.skeleton} />
            <skinnedMesh name="erector_spinae__r" geometry={nodes.erector_spinae__r.geometry} material={nodes.erector_spinae__r.material} skeleton={nodes.erector_spinae__r.skeleton} />
            <skinnedMesh name="finger_extensors__l" geometry={nodes.finger_extensors__l.geometry} material={nodes.finger_extensors__l.material} skeleton={nodes.finger_extensors__l.skeleton} />
            <skinnedMesh name="finger_extensors__r" geometry={nodes.finger_extensors__r.geometry} material={nodes.finger_extensors__r.material} skeleton={nodes.finger_extensors__r.skeleton} />
            <skinnedMesh name="finger_flexors__l" geometry={nodes.finger_flexors__l.geometry} material={nodes.finger_flexors__l.material} skeleton={nodes.finger_flexors__l.skeleton} />
            <skinnedMesh name="finger_flexors__r" geometry={nodes.finger_flexors__r.geometry} material={nodes.finger_flexors__r.material} skeleton={nodes.finger_flexors__r.skeleton} />
            <skinnedMesh name="gastrocnemius__l" geometry={nodes.gastrocnemius__l.geometry} material={nodes.gastrocnemius__l.material} skeleton={nodes.gastrocnemius__l.skeleton} />
            <skinnedMesh name="gastrocnemius__r" geometry={nodes.gastrocnemius__r.geometry} material={nodes.gastrocnemius__r.material} skeleton={nodes.gastrocnemius__r.skeleton} />
            <skinnedMesh name="gluteus_maximus__l" geometry={nodes.gluteus_maximus__l.geometry} material={nodes.gluteus_maximus__l.material} skeleton={nodes.gluteus_maximus__l.skeleton} />
            <skinnedMesh name="gluteus_maximus__r" geometry={nodes.gluteus_maximus__r.geometry} material={nodes.gluteus_maximus__r.material} skeleton={nodes.gluteus_maximus__r.skeleton} />
            <skinnedMesh name="gluteus_medius__l" geometry={nodes.gluteus_medius__l.geometry} material={nodes.gluteus_medius__l.material} skeleton={nodes.gluteus_medius__l.skeleton} />
            <skinnedMesh name="gluteus_medius__r" geometry={nodes.gluteus_medius__r.geometry} material={nodes.gluteus_medius__r.material} skeleton={nodes.gluteus_medius__r.skeleton} />
            <skinnedMesh name="hamstrings__l" geometry={nodes.hamstrings__l.geometry} material={nodes.hamstrings__l.material} skeleton={nodes.hamstrings__l.skeleton} />
            <skinnedMesh name="hamstrings__r" geometry={nodes.hamstrings__r.geometry} material={nodes.hamstrings__r.material} skeleton={nodes.hamstrings__r.skeleton} />
            <skinnedMesh name="hand_intrinsics__l" geometry={nodes.hand_intrinsics__l.geometry} material={nodes.hand_intrinsics__l.material} skeleton={nodes.hand_intrinsics__l.skeleton} />
            <skinnedMesh name="hand_intrinsics__r" geometry={nodes.hand_intrinsics__r.geometry} material={nodes.hand_intrinsics__r.material} skeleton={nodes.hand_intrinsics__r.skeleton} />
            <skinnedMesh name="iliopsoas__l" geometry={nodes.iliopsoas__l.geometry} material={nodes.iliopsoas__l.material} skeleton={nodes.iliopsoas__l.skeleton} />
            <skinnedMesh name="iliopsoas__r" geometry={nodes.iliopsoas__r.geometry} material={nodes.iliopsoas__r.material} skeleton={nodes.iliopsoas__r.skeleton} />
            <skinnedMesh name="latissimus_dorsi__l" geometry={nodes.latissimus_dorsi__l.geometry} material={nodes.latissimus_dorsi__l.material} skeleton={nodes.latissimus_dorsi__l.skeleton} />
            <skinnedMesh name="latissimus_dorsi__r" geometry={nodes.latissimus_dorsi__r.geometry} material={nodes.latissimus_dorsi__r.material} skeleton={nodes.latissimus_dorsi__r.skeleton} />
            <skinnedMesh name="levator_scapulae__l" geometry={nodes.levator_scapulae__l.geometry} material={nodes.levator_scapulae__l.material} skeleton={nodes.levator_scapulae__l.skeleton} />
            <skinnedMesh name="levator_scapulae__r" geometry={nodes.levator_scapulae__r.geometry} material={nodes.levator_scapulae__r.material} skeleton={nodes.levator_scapulae__r.skeleton} />
            <skinnedMesh name="lower_trapezius__l" geometry={nodes.lower_trapezius__l.geometry} material={nodes.lower_trapezius__l.material} skeleton={nodes.lower_trapezius__l.skeleton} />
            <skinnedMesh name="lower_trapezius__r" geometry={nodes.lower_trapezius__r.geometry} material={nodes.lower_trapezius__r.material} skeleton={nodes.lower_trapezius__r.skeleton} />
            <skinnedMesh name="masseter__l" geometry={nodes.masseter__l.geometry} material={nodes.masseter__l.material} skeleton={nodes.masseter__l.skeleton} />
            <skinnedMesh name="masseter__r" geometry={nodes.masseter__r.geometry} material={nodes.masseter__r.material} skeleton={nodes.masseter__r.skeleton} />
            <skinnedMesh name="multifidus__l" geometry={nodes.multifidus__l.geometry} material={nodes.multifidus__l.material} skeleton={nodes.multifidus__l.skeleton} />
            <skinnedMesh name="multifidus__r" geometry={nodes.multifidus__r.geometry} material={nodes.multifidus__r.material} skeleton={nodes.multifidus__r.skeleton} />
            <skinnedMesh name="pectoralis_major__l" geometry={nodes.pectoralis_major__l.geometry} material={nodes.pectoralis_major__l.material} skeleton={nodes.pectoralis_major__l.skeleton} />
            <skinnedMesh name="pectoralis_major__r" geometry={nodes.pectoralis_major__r.geometry} material={nodes.pectoralis_major__r.material} skeleton={nodes.pectoralis_major__r.skeleton} />
            <skinnedMesh name="pectoralis_minor__l" geometry={nodes.pectoralis_minor__l.geometry} material={nodes.pectoralis_minor__l.material} skeleton={nodes.pectoralis_minor__l.skeleton} />
            <skinnedMesh name="pectoralis_minor__r" geometry={nodes.pectoralis_minor__r.geometry} material={nodes.pectoralis_minor__r.material} skeleton={nodes.pectoralis_minor__r.skeleton} />
            <skinnedMesh name="peroneals__l" geometry={nodes.peroneals__l.geometry} material={nodes.peroneals__l.material} skeleton={nodes.peroneals__l.skeleton} />
            <skinnedMesh name="peroneals__r" geometry={nodes.peroneals__r.geometry} material={nodes.peroneals__r.material} skeleton={nodes.peroneals__r.skeleton} />
            <skinnedMesh name="piriformis__l" geometry={nodes.piriformis__l.geometry} material={nodes.piriformis__l.material} skeleton={nodes.piriformis__l.skeleton} />
            <skinnedMesh name="piriformis__r" geometry={nodes.piriformis__r.geometry} material={nodes.piriformis__r.material} skeleton={nodes.piriformis__r.skeleton} />
            <skinnedMesh name="pronators__l" geometry={nodes.pronators__l.geometry} material={nodes.pronators__l.material} skeleton={nodes.pronators__l.skeleton} />
            <skinnedMesh name="pronators__r" geometry={nodes.pronators__r.geometry} material={nodes.pronators__r.material} skeleton={nodes.pronators__r.skeleton} />
            <skinnedMesh name="pterygoids__l" geometry={nodes.pterygoids__l.geometry} material={nodes.pterygoids__l.material} skeleton={nodes.pterygoids__l.skeleton} />
            <skinnedMesh name="pterygoids__r" geometry={nodes.pterygoids__r.geometry} material={nodes.pterygoids__r.material} skeleton={nodes.pterygoids__r.skeleton} />
            <skinnedMesh name="quadratus_lumborum__l" geometry={nodes.quadratus_lumborum__l.geometry} material={nodes.quadratus_lumborum__l.material} skeleton={nodes.quadratus_lumborum__l.skeleton} />
            <skinnedMesh name="quadratus_lumborum__r" geometry={nodes.quadratus_lumborum__r.geometry} material={nodes.quadratus_lumborum__r.material} skeleton={nodes.quadratus_lumborum__r.skeleton} />
            <skinnedMesh name="quadriceps__l" geometry={nodes.quadriceps__l.geometry} material={nodes.quadriceps__l.material} skeleton={nodes.quadriceps__l.skeleton} />
            <skinnedMesh name="quadriceps__r" geometry={nodes.quadriceps__r.geometry} material={nodes.quadriceps__r.material} skeleton={nodes.quadriceps__r.skeleton} />
            <skinnedMesh name="rectus_abdominis__l" geometry={nodes.rectus_abdominis__l.geometry} material={nodes.rectus_abdominis__l.material} skeleton={nodes.rectus_abdominis__l.skeleton} />
            <skinnedMesh name="rectus_abdominis__r" geometry={nodes.rectus_abdominis__r.geometry} material={nodes.rectus_abdominis__r.material} skeleton={nodes.rectus_abdominis__r.skeleton} />
            <skinnedMesh name="rectus_femoris__l" geometry={nodes.rectus_femoris__l.geometry} material={nodes.rectus_femoris__l.material} skeleton={nodes.rectus_femoris__l.skeleton} />
            <skinnedMesh name="rectus_femoris__r" geometry={nodes.rectus_femoris__r.geometry} material={nodes.rectus_femoris__r.material} skeleton={nodes.rectus_femoris__r.skeleton} />
            <skinnedMesh name="rhomboids__l" geometry={nodes.rhomboids__l.geometry} material={nodes.rhomboids__l.material} skeleton={nodes.rhomboids__l.skeleton} />
            <skinnedMesh name="rhomboids__r" geometry={nodes.rhomboids__r.geometry} material={nodes.rhomboids__r.material} skeleton={nodes.rhomboids__r.skeleton} />
            <skinnedMesh name="rotator_cuff__l" geometry={nodes.rotator_cuff__l.geometry} material={nodes.rotator_cuff__l.material} skeleton={nodes.rotator_cuff__l.skeleton} />
            <skinnedMesh name="rotator_cuff__r" geometry={nodes.rotator_cuff__r.geometry} material={nodes.rotator_cuff__r.material} skeleton={nodes.rotator_cuff__r.skeleton} />
            <skinnedMesh name="scalenes__l" geometry={nodes.scalenes__l.geometry} material={nodes.scalenes__l.material} skeleton={nodes.scalenes__l.skeleton} />
            <skinnedMesh name="scalenes__r" geometry={nodes.scalenes__r.geometry} material={nodes.scalenes__r.material} skeleton={nodes.scalenes__r.skeleton} />
            <skinnedMesh name="serratus_anterior__l" geometry={nodes.serratus_anterior__l.geometry} material={nodes.serratus_anterior__l.material} skeleton={nodes.serratus_anterior__l.skeleton} />
            <skinnedMesh name="serratus_anterior__r" geometry={nodes.serratus_anterior__r.geometry} material={nodes.serratus_anterior__r.material} skeleton={nodes.serratus_anterior__r.skeleton} />
            <skinnedMesh name="soleus__l" geometry={nodes.soleus__l.geometry} material={nodes.soleus__l.material} skeleton={nodes.soleus__l.skeleton} />
            <skinnedMesh name="soleus__r" geometry={nodes.soleus__r.geometry} material={nodes.soleus__r.material} skeleton={nodes.soleus__r.skeleton} />
            <skinnedMesh name="splenius__l" geometry={nodes.splenius__l.geometry} material={nodes.splenius__l.material} skeleton={nodes.splenius__l.skeleton} />
            <skinnedMesh name="splenius__r" geometry={nodes.splenius__r.geometry} material={nodes.splenius__r.material} skeleton={nodes.splenius__r.skeleton} />
            <skinnedMesh name="sternocleidomastoid__l" geometry={nodes.sternocleidomastoid__l.geometry} material={nodes.sternocleidomastoid__l.material} skeleton={nodes.sternocleidomastoid__l.skeleton} />
            <skinnedMesh name="sternocleidomastoid__r" geometry={nodes.sternocleidomastoid__r.geometry} material={nodes.sternocleidomastoid__r.material} skeleton={nodes.sternocleidomastoid__r.skeleton} />
            <skinnedMesh name="suboccipitals__l" geometry={nodes.suboccipitals__l.geometry} material={nodes.suboccipitals__l.material} skeleton={nodes.suboccipitals__l.skeleton} />
            <skinnedMesh name="suboccipitals__r" geometry={nodes.suboccipitals__r.geometry} material={nodes.suboccipitals__r.material} skeleton={nodes.suboccipitals__r.skeleton} />
            <skinnedMesh name="supinator__l" geometry={nodes.supinator__l.geometry} material={nodes.supinator__l.material} skeleton={nodes.supinator__l.skeleton} />
            <skinnedMesh name="supinator__r" geometry={nodes.supinator__r.geometry} material={nodes.supinator__r.material} skeleton={nodes.supinator__r.skeleton} />
            <skinnedMesh name="temporalis__l" geometry={nodes.temporalis__l.geometry} material={nodes.temporalis__l.material} skeleton={nodes.temporalis__l.skeleton} />
            <skinnedMesh name="temporalis__r" geometry={nodes.temporalis__r.geometry} material={nodes.temporalis__r.material} skeleton={nodes.temporalis__r.skeleton} />
            <skinnedMesh name="tfl__l" geometry={nodes.tfl__l.geometry} material={nodes.tfl__l.material} skeleton={nodes.tfl__l.skeleton} />
            <skinnedMesh name="tfl__r" geometry={nodes.tfl__r.geometry} material={nodes.tfl__r.material} skeleton={nodes.tfl__r.skeleton} />
            <skinnedMesh name="tibialis_anterior__l" geometry={nodes.tibialis_anterior__l.geometry} material={nodes.tibialis_anterior__l.material} skeleton={nodes.tibialis_anterior__l.skeleton} />
            <skinnedMesh name="tibialis_anterior__r" geometry={nodes.tibialis_anterior__r.geometry} material={nodes.tibialis_anterior__r.material} skeleton={nodes.tibialis_anterior__r.skeleton} />
            <skinnedMesh name="tibialis_posterior__l" geometry={nodes.tibialis_posterior__l.geometry} material={nodes.tibialis_posterior__l.material} skeleton={nodes.tibialis_posterior__l.skeleton} />
            <skinnedMesh name="tibialis_posterior__r" geometry={nodes.tibialis_posterior__r.geometry} material={nodes.tibialis_posterior__r.material} skeleton={nodes.tibialis_posterior__r.skeleton} />
            <skinnedMesh name="transversus_abdominis__l" geometry={nodes.transversus_abdominis__l.geometry} material={nodes.transversus_abdominis__l.material} skeleton={nodes.transversus_abdominis__l.skeleton} />
            <skinnedMesh name="transversus_abdominis__r" geometry={nodes.transversus_abdominis__r.geometry} material={nodes.transversus_abdominis__r.material} skeleton={nodes.transversus_abdominis__r.skeleton} />
            <skinnedMesh name="triceps_brachii__l" geometry={nodes.triceps_brachii__l.geometry} material={nodes.triceps_brachii__l.material} skeleton={nodes.triceps_brachii__l.skeleton} />
            <skinnedMesh name="triceps_brachii__r" geometry={nodes.triceps_brachii__r.geometry} material={nodes.triceps_brachii__r.material} skeleton={nodes.triceps_brachii__r.skeleton} />
            <skinnedMesh name="upper_trapezius__l" geometry={nodes.upper_trapezius__l.geometry} material={nodes.upper_trapezius__l.material} skeleton={nodes.upper_trapezius__l.skeleton} />
            <skinnedMesh name="upper_trapezius__r" geometry={nodes.upper_trapezius__r.geometry} material={nodes.upper_trapezius__r.material} skeleton={nodes.upper_trapezius__r.skeleton} />
            <skinnedMesh name="wrist_extensors__l" geometry={nodes.wrist_extensors__l.geometry} material={nodes.wrist_extensors__l.material} skeleton={nodes.wrist_extensors__l.skeleton} />
            <skinnedMesh name="wrist_extensors__r" geometry={nodes.wrist_extensors__r.geometry} material={nodes.wrist_extensors__r.material} skeleton={nodes.wrist_extensors__r.skeleton} />
            <skinnedMesh name="wrist_flexors__l" geometry={nodes.wrist_flexors__l.geometry} material={nodes.wrist_flexors__l.material} skeleton={nodes.wrist_flexors__l.skeleton} />
            <skinnedMesh name="wrist_flexors__r" geometry={nodes.wrist_flexors__r.geometry} material={nodes.wrist_flexors__r.material} skeleton={nodes.wrist_flexors__r.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/squat_interactive-transformed.glb')
